export default [
  {
    categoria: "Básicos",
    ejemplos: [
      {
        id: "b0",
        titulo: "Interleaving",
        texto: [
          "Thread(2){",
          "\tprint('rojo')",
          "}",
          "",
          "Thread(2){",
          "\tprint('azul')",
          "}",
        ].join("\n"),
        razon: "Dos pares de threads imprimiendo colores — muestra interleaving básico",
      },
      {
        id: "b1",
        titulo: "Lectura vieja",
        texto: [
          "global Int n = 0",
          "",
          "Thread(1){",
          "\tn = n + 1",
          "}",
          "",
          "Thread(1){",
          "\tprint(n)",
          "}",
        ].join("\n"),
        razon: "Thread suma global e imprime — la lectura puede ser anterior a la escritura del otro thread",
      },
      {
        id: "b2",
        titulo: "Race condition",
        texto: [
          "global Int n = 0",
          "",
          "Thread(2){",
          "\tn = n + 1",
          "}",
        ].join("\n"),
        razon: "Dos threads incrementando la misma variable — clásico ejemplo de pérdida de escritura",
      },
      {
        id: "b3",
        titulo: "Suma cruzada",
        texto: [
          "global Int x = 0",
          "global Int y = 0",
          "",
          "Thread(1){",
          "\ty = x + 1",
          "}",
          "",
          "Thread(1){",
          "\tx = y + 1",
          "}",
        ].join("\n"),
        razon: "Dos threads con variables que dependen entre sí — pérdida de suma cruzada",
      },
    ],
  },
  {
    categoria: "Control de flujo",
    ejemplos: [
      {
        id: "c0",
        titulo: "While compartido",
        texto: [
          "global Int n = 1",
          "",
          "Thread(2){",
          "\twhile(n == 1){",
          "\t\tn = n + 1",
          "\t}",
          "}",
        ].join("\n"),
        razon: "Dos threads esperando la misma condición compartida",
      },
      {
        id: "c1",
        titulo: "While con print",
        texto: [
          "global Int n = 0",
          "",
          "Thread(1){",
          "\twhile(n < 2){",
          "\t\tprint(n)",
          "\t}",
          "}",
          "",
          "Thread(1){",
          "\tn = n + 1",
          "\tn = n + 1",
          "}",
        ].join("\n"),
        razon: "Un thread puede leer valores viejos mientras el otro actualiza",
      },
      {
        id: "c2",
        titulo: "Repeat",
        texto: [
          "global Int n = 0",
          "",
          "Thread(2){",
          "\trepeat(3){",
          "\t\tn = n + 1",
          "\t}",
          "}",
        ].join("\n"),
        razon: "Dos threads repitiendo un bloque 3 veces — posible pérdida de incrementos",
      },
      {
        id: "c3",
        titulo: "For",
        texto: [
          "global Int n = 0",
          "",
          "Thread(2){",
          "\tfor(local Int i = 0; i < 3; i = i + 1){",
          "\t\tn = n + 1",
          "\t}",
          "}",
        ].join("\n"),
        razon: "Dos threads suman n 3 veces cada uno con for",
      },
      {
        id: "c4",
        titulo: "For-each",
        texto: [
          "global Int n = 0",
          "",
          "Thread(1){",
          "\tfor(x : [1,2,3]){",
          "\t\tn = n + x",
          "\t}",
          "}",
        ].join("\n"),
        razon: "Suma los elementos de una lista con for-each",
      },
    ],
  },
  {
    categoria: "Semáforos",
    ejemplos: [
      {
        id: "s0",
        titulo: "Mutex básico",
        texto: [
          "global Int contador = 0",
          "global Semaphore mutex = new Semaphore(1)",
          "",
          "Thread(2){",
          "\tmutex.acquire()",
          "\tcontador = contador + 1",
          "\tmutex.release()",
          "}",
        ].join("\n"),
        razon: "Mutex: 2 threads incrementan contador con exclusión mutua",
      },
      {
        id: "s1",
        titulo: "Split mutex",
        texto: [
          "global Semaphore turnoA = new Semaphore(1)",
          "global Semaphore turnoB = new Semaphore(0)",
          "",
          "Thread(1, 'A'){",
          "\twhile(true){",
          "\t\tturnoA.acquire()",
          "\t\tprint('A')",
          "\t\tturnoB.release()",
          "\t}",
          "}",
          "",
          "Thread(1, 'B'){",
          "\twhile(true){",
          "\t\tturnoB.acquire()",
          "\t\tprint('B')",
          "\t\tturnoA.release()",
          "\t}",
          "}",
        ].join("\n"),
        razon: "Split mutex: A y B se alternan estrictamente imprimiendo su letra",
      },
      {
        id: "s2",
        titulo: "Productor-Consumidor",
        texto: [
          "global Int buffer = 0",
          "global Int producido = 0",
          "global Semaphore vacio = new Semaphore(1)",
          "global Semaphore lleno = new Semaphore(0)",
          "",
          "Thread(1, 'Productor'){",
          "\tvacio.acquire()",
          "\tproducido = producido + 1",
          "\tbuffer = producido",
          "\tprint(buffer)",
          "\tlleno.release()",
          "}",
          "",
          "Thread(1, 'Consumidor'){",
          "\tlleno.acquire()",
          "\tlocal Int item = buffer",
          "\tvacio.release()",
          "\tprint(item)",
          "}",
        ].join("\n"),
        razon: "Productor-Consumidor: buffer de tamaño 1 sincronizado con semáforos",
      },
      {
        id: "s3",
        titulo: "Lector-Escritor",
        texto: [
          "global Int lectores = 0",
          "global Semaphore mutexLectores = new Semaphore(1)",
          "global Semaphore escritura = new Semaphore(1)",
          "global Int dato = 0",
          "",
          "Thread(2, 'Lector'){",
          "\tmutexLectores.acquire()",
          "\tlectores = lectores + 1",
          "\tif(lectores == 1){",
          "\t\tescritu ra.acquire()",
          "\t}",
          "\tmutexLectores.release()",
          "\tprint(dato)",
          "\tmutexLectores.acquire()",
          "\tlectores = lectores - 1",
          "\tif(lectores == 0){",
          "\t\tescritu ra.release()",
          "\t}",
          "\tmutexLectores.release()",
          "}",
          "",
          "Thread(1, 'Escritor'){",
          "\tescritu ra.acquire()",
          "\tdato = dato + 1",
          "\tescritu ra.release()",
          "}",
        ].join("\n").replace(/escritu ra/g, "escritura"),
        razon: "Lector-Escritor: múltiples lectores simultáneos, escritor con exclusión total",
      },
      {
        id: "s4",
        titulo: "Array de semáforos",
        texto: [
          "global Int contador = 0",
          "global Semaphore[] sems = new Semaphore[2](1)",
          "",
          "Thread(2){",
          "\tlocal Int id = getId()",
          "\tsems[id].acquire()",
          "\tcontador = contador + 1",
          "\tsems[id].release()",
          "}",
        ].join("\n"),
        razon: "Cada thread usa su propio semáforo del array",
      },
      {
        id: "s5",
        titulo: "Semáforo débil",
        texto: [
          "global Semaphore s = new Semaphore(0)",
          "",
          "Thread(3, 'Esperando'){",
          "\tlocal Int id = getId()",
          "\ts.acquire()",
          "\tprint(id)",
          "}",
          "",
          "Thread(1, 'Liberador'){",
          "\ts.release()",
          "\ts.release()",
          "\ts.release()",
          "}",
        ].join("\n"),
        razon: "Semáforo débil: los threads se despiertan en orden aleatorio — el print puede salir en cualquier orden",
      },
      {
        id: "s6",
        titulo: "Semáforo fuerte",
        texto: [
          "global Semaphore s = new Semaphore(0, true)",
          "",
          "Thread(3, 'Esperando'){",
          "\tlocal Int id = getId()",
          "\ts.acquire()",
          "\tprint(id)",
          "}",
          "",
          "Thread(1, 'Liberador'){",
          "\ts.release()",
          "\ts.release()",
          "\ts.release()",
          "}",
        ].join("\n"),
        razon: "Semáforo fuerte (FIFO): los threads se despiertan en el orden en que llegaron — el print siempre sale en el mismo orden",
      },
    ],
  },
  {
    categoria: "Algoritmos",
    ejemplos: [
      {
        id: "a0",
        titulo: "Bakery",
        texto: [
          "global List ticket = [0,0]",
          "global List pidiendoTicket = [false,false]",
          "global Int n = 2",
          "global Int seccionCritica = 0",
          "",
          "Thread(2){",
          "\tlocal Int id = getId()",
          "\tpidiendoTicket[id] = true",
          "\tticket[id] = 1 + ticket.maximum()",
          "\tpidiendoTicket[id] = false",
          "\tfor(local Int j=0;j<n;j=j+1){",
          "\t\twhile(pidiendoTicket[j]){",
          "\t\t}",
          "\t\twhile(ticket[j]!=0&&(ticket[j]<ticket[id]||(ticket[j]==ticket[id]&&j<id))){",
          "\t\t}",
          "\t}",
          "\tseccionCritica = seccionCritica + 1",
          "\tticket[id] = 0",
          "}",
        ].join("\n"),
        razon: "Algoritmo de Bakery (Lamport): exclusión mutua sin semáforos",
      },
      {
        id: "a2",
        titulo: "Peterson",
        texto: [
          "global Bool flag0 = false",
          "global Bool flag1 = false",
          "global Int turno = 0",
          "global Int seccionCritica = 0",
          "",
          "Thread(1, 'T0'){",
          "\tflag0 = true",
          "\tturno = 1",
          "\twhile (flag1 == true && turno == 1) {",
          "\t}",
          "\tseccionCritica = seccionCritica + 1",
          "\tflag0 = false",
          "}",
          "",
          "Thread(1, 'T1'){",
          "\tflag1 = true",
          "\tturno = 0",
          "\twhile (flag0 == true && turno == 0) {",
          "\t}",
          "\tseccionCritica = seccionCritica + 1",
          "\tflag1 = false",
          "}",
        ].join("\n"),
        razon: "Algoritmo de Peterson: exclusión mutua para 2 threads sin semáforos — seccionCritica siempre termina en 2, nunca hay dos threads adentro a la vez",
      },
      {
        id: "a3",
        titulo: "Filósofos (con deadlock)",
        texto: [
          "// Todos toman izquierdo antes que derecho — espera circular posible",
          "global Semaphore[] tenedor = new Semaphore[5](1)",
          "",
          "Thread(5, 'Filosofo'){",
          "\tlocal Int id = getId()",
          "\tlocal Int izq = id % 5",
          "\tlocal Int der = (id + 1) % 5",
          "\ttenedor[izq].acquire()",
          "\ttenedor[der].acquire()",
          "\tprint(id)",
          "\ttenedor[der].release()",
          "\ttenedor[izq].release()",
          "}",
        ].join("\n"),
        razon: "5 filósofos, 5 tenedores — todos toman izquierdo antes que derecho, formando una espera circular: deadlock posible con probabilidad alta",
      },
      {
        id: "a4",
        titulo: "Filósofos (sin deadlock)",
        texto: [
          "// Solución asimétrica: el filósofo 4 toma primero el tenedor más chico",
          "// Rompe la espera circular — nunca hay deadlock",
          "global Semaphore[] tenedor = new Semaphore[5](1)",
          "",
          "Thread(4, 'Filosofo'){",
          "\tlocal Int id = getId()",
          "\tlocal Int izq = id % 5",
          "\tlocal Int der = (id + 1) % 5",
          "\ttenedor[izq].acquire()",
          "\ttenedor[der].acquire()",
          "\tprint(id)",
          "\ttenedor[der].release()",
          "\ttenedor[izq].release()",
          "}",
          "",
          "Thread(1, 'Filosofo4'){",
          "\ttenedor[0].acquire()",
          "\ttenedor[4].acquire()",
          "\tprint(4)",
          "\ttenedor[4].release()",
          "\ttenedor[0].release()",
          "}",
        ].join("\n"),
        razon: "Solución asimétrica: el filósofo 4 toma primero el tenedor 0 (el más chico) en vez del 4, rompiendo la espera circular — siempre terminan los 5",
      },
      {
        id: "a1",
        titulo: "Funciones",
        texto: [
          "global Int contador = 0",
          "",
          "function incrementar(Int x) {",
          "\treturn x + 1",
          "}",
          "",
          "Thread(2) {",
          "\tlocal Int leido = contador",
          "\tlocal Int nuevo = incrementar(leido)",
          "\tcontador = nuevo",
          "}",
        ].join("\n"),
        razon: "Race condition visible a través de llamadas a función",
      },
    ],
  },
  {
    categoria: "Errores",
    ejemplos: [
      {
        id: "e0",
        titulo: "Variable no declarada",
        texto: [
          "Thread(1){",
          "\tcontador = contador + 1",
          "}",
        ].join("\n"),
        razon: "Usar una variable sin declararla — error de runtime",
      },
      {
        id: "e1",
        titulo: "Typo en nombre",
        texto: [
          "global Int contador = 0",
          "",
          "Thread(1){",
          "\tcontadorr = contadorr + 1",
          "}",
        ].join("\n"),
        razon: "Error de tipeo en el nombre de una variable",
      },
      {
        id: "e2",
        titulo: "Sintaxis rota",
        texto: [
          "global Int n = 0",
          "",
          "Thread(2){",
          "\tif(n == 0{",
          "\t\tn = n + 1",
          "\t}",
          "}",
        ].join("\n"),
        razon: "Paréntesis sin cerrar en el if — error de parse",
      },
      {
        id: "e3",
        titulo: "Índice fuera de rango",
        texto: [
          "global List nums = [1, 2, 3]",
          "",
          "Thread(1){",
          "\tprint(nums[5])",
          "}",
        ].join("\n"),
        razon: "Acceso a un índice que no existe en la lista",
      },
      {
        id: "e4",
        titulo: "Deadlock con semáforos",
        texto: [
          "global Semaphore a = new Semaphore(1)",
          "global Semaphore b = new Semaphore(1)",
          "",
          "Thread(1, 'T1'){",
          "\ta.acquire()",
          "\tb.acquire()",
          "\tb.release()",
          "\ta.release()",
          "}",
          "",
          "Thread(1, 'T2'){",
          "\tb.acquire()",
          "\ta.acquire()",
          "\ta.release()",
          "\tb.release()",
          "}",
        ].join("\n"),
        razon: "Deadlock clásico: T1 toma A y espera B, T2 toma B y espera A — ninguno puede avanzar",
      },
      {
        id: "e5",
        titulo: "Deadlock en monitor (sin productor)",
        texto: [
          "monitor Buffer {",
          "\tcondition hayDato",
          "\tlocal Bool vacio = true",
          "",
          "\tfunction consumir() {",
          "\t\twhile (vacio == true) {",
          "\t\t\thayDato.wait()",
          "\t\t}",
          "\t}",
          "}",
          "",
          "global Buffer buf = new Buffer()",
          "",
          "Thread(2, 'Consumidor'){",
          "\tbuf.consumir()",
          "}",
        ].join("\n"),
        razon: "Los consumidores esperan en hayDato pero no hay ningún productor que notifique — todos quedan bloqueados para siempre",
      },
    ],
  },
  {
    categoria: "Clases",
    ejemplos: [
      {
        id: "cl0",
        titulo: "Contador compartido",
        texto: [
          "class Contador {",
          "\tlocal Int valor = 0",
          "",
          "\tconstructor(Int inicial) {",
          "\t\tvalor = inicial",
          "\t}",
          "",
          "\tfunction incrementar() {",
          "\t\tvalor = valor + 1",
          "\t}",
          "",
          "\tfunction getValor() {",
          "\t\treturn valor",
          "\t}",
          "}",
          "",
          "global Contador c = new Contador(0)",
          "",
          "Thread(2){",
          "\tc.incrementar()",
          "\tprint(c.getValor())",
          "}",
        ].join("\n"),
        razon: "Race condition clásica: dos threads incrementan el mismo objeto — el interleaving dentro de incrementar() puede causar pérdida de escritura",
      },
      {
        id: "cl1",
        titulo: "Instancias locales (sin race)",
        texto: [
          "class Contador {",
          "\tlocal Int valor = 0",
          "",
          "\tconstructor(Int inicial) {",
          "\t\tvalor = inicial",
          "\t}",
          "",
          "\tfunction incrementar() {",
          "\t\tvalor = valor + 1",
          "\t}",
          "",
          "\tfunction getValor() {",
          "\t\treturn valor",
          "\t}",
          "}",
          "",
          "Thread(2){",
          "\tlocal Contador c = new Contador(0)",
          "\tc.incrementar()",
          "\tc.incrementar()",
          "\tprint(c.getValor())",
          "}",
        ].join("\n"),
        razon: "Cada thread crea su propia instancia local — no hay memoria compartida, no hay race condition",
      },
      {
        id: "cl2",
        titulo: "Contador con semáforo",
        texto: [
          "class Contador {",
          "\tlocal Int valor = 0",
          "",
          "\tconstructor(Int inicial) {",
          "\t\tvalor = inicial",
          "\t}",
          "",
          "\tfunction incrementar() {",
          "\t\tvalor = valor + 1",
          "\t}",
          "",
          "\tfunction getValor() {",
          "\t\treturn valor",
          "\t}",
          "}",
          "",
          "global Contador c = new Contador(0)",
          "global Semaphore mutex = new Semaphore(1)",
          "global Semaphore listo = new Semaphore(0)",
          "",
          "Thread(3, 'Escritor'){",
          "\tmutex.acquire()",
          "\tc.incrementar()",
          "\tmutex.release()",
          "\tlisto.release()",
          "}",
          "",
          "Thread(1, 'Lector'){",
          "\tlisto.acquire()",
          "\tlisto.acquire()",
          "\tlisto.acquire()",
          "\tprint(c.getValor())",
          "}",
        ].join("\n"),
        razon: "El lector espera a los 3 escritores con 3 acquires — siempre imprime 3 sin importar el interleaving",
      },
      {
        id: "cl3",
        titulo: "Estado inconsistente",
        texto: [
          "class Punto {",
          "\tlocal Int x = 0",
          "\tlocal Int y = 0",
          "",
          "\tfunction mover(Int nx, Int ny) {",
          "\t\tx = nx",
          "\t\ty = ny",
          "\t}",
          "",
          "\tfunction leer() {",
          "\t\treturn x + y",
          "\t}",
          "}",
          "",
          "global Punto p = new Punto()",
          "",
          "Thread(2, 'Escritor'){",
          "\tp.mover(10, 10)",
          "}",
          "",
          "Thread(2, 'Lector'){",
          "\tprint(p.leer())",
          "}",
        ].join("\n"),
        razon: "Sin semáforo, un lector puede ver x=10 e y=0 — un estado que nunca debería existir. El resultado puede ser 0, 10 o 20",
      },
      {
        id: "cl4",
        titulo: "this — delegación entre métodos",
        texto: [
          "class Contador {",
          "\tlocal Int valor = 0",
          "",
          "\tfunction incrementar() {",
          "\t\tvalor = valor + 1",
          "\t}",
          "",
          "\tfunction incrementarDos() {",
          "\t\tthis.incrementar()",
          "\t\tthis.incrementar()",
          "\t}",
          "",
          "\tfunction getValor() {",
          "\t\treturn valor",
          "\t}",
          "}",
          "",
          "global Contador c = new Contador(0)",
          "",
          "Thread(2){",
          "\tc.incrementarDos()",
          "\tprint(c.getValor())",
          "}",
        ].join("\n"),
        razon: "this llama a métodos de la misma instancia — el interleaving puede ocurrir entre los dos incrementar() internos, mostrando race condition dentro de la delegación",
      },
    ],
  },
  {
    categoria: "Monitores",
    ejemplos: [
      {
        id: "m0",
        titulo: "Exclusión mutua",
        texto: [
          "monitor Contador {",
          "\tlocal Int valor = 0",
          "",
          "\tfunction incrementar() {",
          "\t\tvalor = valor + 1",
          "\t\tprint(valor)",
          "\t}",
          "}",
          "",
          "global Contador c = new Contador()",
          "",
          "Thread(3){",
          "\tc.incrementar()",
          "}",
        ].join("\n"),
        razon: "El monitor garantiza exclusión mutua — solo un thread ejecuta incrementar() a la vez, nunca hay pérdida de escritura",
      },
      {
        id: "m1",
        titulo: "Productor-Consumidor",
        texto: [
          "monitor Buffer {",
          "\tlocal Int dato = 0",
          "\tlocal Bool lleno = false",
          "",
          "\tfunction depositar(Int v) {",
          "\t\twhile (lleno == true) {",
          "\t\t\twait()",
          "\t\t}",
          "\t\tdato = v",
          "\t\tlleno = true",
          "\t\tnotifyAll()",
          "\t}",
          "",
          "\tfunction retirar() {",
          "\t\twhile (lleno == false) {",
          "\t\t\twait()",
          "\t\t}",
          "\t\tlocal Int tmp = dato",
          "\t\tlleno = false",
          "\t\tnotifyAll()",
          "\t\treturn tmp",
          "\t}",
          "}",
          "",
          "global Buffer b = new Buffer()",
          "",
          "Thread(1, 'Productor'){",
          "\tb.depositar(42)",
          "\tb.depositar(99)",
          "}",
          "",
          "Thread(1, 'Consumidor'){",
          "\tprint(b.retirar())",
          "\tprint(b.retirar())",
          "}",
        ].join("\n"),
        razon: "Productor-Consumidor con monitor — el buffer de tamaño 1 se sincroniza con wait/notify sin semáforos explícitos",
      },
      {
        id: "m3",
        titulo: "Lectores-Escritores",
        texto: [
          "monitor Database {",
          "\tlocal Int nLectores = 0",
          "\tlocal Int nEscritores = 0",
          "\tlocal Int dato = 0",
          "",
          "\tfunction inicioLectura() {",
          "\t\twhile (nEscritores != 0) {",
          "\t\t\twait()",
          "\t\t}",
          "\t\tnLectores = nLectores + 1",
          "\t}",
          "",
          "\tfunction finLectura() {",
          "\t\tnLectores = nLectores - 1",
          "\t\tif (nLectores == 0) {",
          "\t\t\tnotify()",
          "\t\t}",
          "\t}",
          "",
          "\tfunction inicioEscritura() {",
          "\t\twhile (nEscritores != 0 || nLectores != 0) {",
          "\t\t\twait()",
          "\t\t}",
          "\t\tnEscritores = 1",
          "\t}",
          "",
          "\tfunction finEscritura() {",
          "\t\tnEscritores = 0",
          "\t\tnotifyAll()",
          "\t}",
          "",
          "\tfunction leer() {",
          "\t\treturn dato",
          "\t}",
          "",
          "\tfunction escribir(Int v) {",
          "\t\tdato = v",
          "\t}",
          "}",
          "",
          "global Database db = new Database()",
          "",
          "Thread(3, 'Lector'){",
          "\tdb.inicioLectura()",
          "\tprint(db.leer())",
          "\tdb.finLectura()",
          "}",
          "",
          "Thread(2, 'Escritor'){",
          "\tlocal Int id = getId()",
          "\tdb.inicioEscritura()",
          "\tdb.escribir(id)",
          "\tdb.finEscritura()",
          "}",
        ].join("\n"),
        razon: "Lectores-Escritores con monitor: múltiples lectores simultáneos, escritor con exclusión total — finLectura notifica al escritor esperando, finEscritura despierta a todos",
      },
      {
        id: "m4",
        titulo: "Lectores-Escritores (prioridad escritores)",
        texto: [
          "monitor Database {",
          "\tlocal Int nLectores = 0",
          "\tlocal Int nEscritores = 0",
          "\tlocal Int nEsperandoEscribir = 0",
          "\tlocal Int dato = 0",
          "",
          "\tfunction inicioLectura() {",
          "\t\twhile (nEscritores != 0 || nEsperandoEscribir != 0) {",
          "\t\t\twait()",
          "\t\t}",
          "\t\tnLectores = nLectores + 1",
          "\t}",
          "",
          "\tfunction finLectura() {",
          "\t\tnLectores = nLectores - 1",
          "\t\tif (nLectores == 0) {",
          "\t\t\tnotify()",
          "\t\t}",
          "\t}",
          "",
          "\tfunction inicioEscritura() {",
          "\t\tnEsperandoEscribir = nEsperandoEscribir + 1",
          "\t\twhile (nEscritores != 0 || nLectores != 0) {",
          "\t\t\twait()",
          "\t\t}",
          "\t\tnEsperandoEscribir = nEsperandoEscribir - 1",
          "\t\tnEscritores = 1",
          "\t}",
          "",
          "\tfunction finEscritura() {",
          "\t\tnEscritores = 0",
          "\t\tnotifyAll()",
          "\t}",
          "",
          "\tfunction leer() {",
          "\t\treturn dato",
          "\t}",
          "",
          "\tfunction escribir(Int v) {",
          "\t\tdato = v",
          "\t}",
          "}",
          "",
          "global Database db = new Database()",
          "",
          "Thread(3, 'Lector'){",
          "\tdb.inicioLectura()",
          "\tprint(db.leer())",
          "\tdb.finLectura()",
          "}",
          "",
          "Thread(2, 'Escritor'){",
          "\tlocal Int id = getId()",
          "\tdb.inicioEscritura()",
          "\tdb.escribir(id)",
          "\tdb.finEscritura()",
          "}",
        ].join("\n"),
        razon: "Igual que el anterior pero los escritores tienen prioridad: si hay un escritor esperando, los nuevos lectores no pueden entrar — evita inanición de escritores",
      },
      {
        id: "m5",
        titulo: "Barrera (rendezvous)",
        texto: [
          "monitor Barrera {",
          "\tlocal Int total = 3",
          "\tlocal Int llegaron = 0",
          "",
          "\tfunction esperar() {",
          "\t\tllegaron = llegaron + 1",
          "\t\tif (llegaron < total) {",
          "\t\t\twait()",
          "\t\t} else {",
          "\t\t\tnotifyAll()",
          "\t\t}",
          "\t}",
          "}",
          "",
          "global Barrera miBarrera = new Barrera()",
          "",
          "Thread(1, 'T1'){",
          "\tprint('a')",
          "\tmiBarrera.esperar()",
          "\tprint(1)",
          "}",
          "",
          "Thread(1, 'T2'){",
          "\tprint('b')",
          "\tmiBarrera.esperar()",
          "\tprint(2)",
          "}",
          "",
          "Thread(1, 'T3'){",
          "\tprint('c')",
          "\tmiBarrera.esperar()",
          "\tprint(3)",
          "}",
        ].join("\n"),
        razon: "Barrera de 3 threads: ninguno pasa a la segunda fase hasta que todos llegaron — los print('a','b','c') pueden salir en cualquier orden, pero los print(1,2,3) siempre salen después de todos",
      },
      {
        id: "m6",
        titulo: "Variables de condición explícitas",
        texto: [
          "monitor Buffer {",
          "\tcondition hayDato",
          "\tcondition hayEspacio",
          "\tlocal Int dato = 0",
          "\tlocal Bool lleno = false",
          "",
          "\tfunction depositar(Int v) {",
          "\t\twhile (lleno == true) {",
          "\t\t\thayEspacio.wait()",
          "\t\t}",
          "\t\tdato = v",
          "\t\tlleno = true",
          "\t\thayDato.notify()",
          "\t}",
          "",
          "\tfunction retirar() {",
          "\t\twhile (lleno == false) {",
          "\t\t\thayDato.wait()",
          "\t\t}",
          "\t\tlocal Int tmp = dato",
          "\t\tlleno = false",
          "\t\thayEspacio.notify()",
          "\t\treturn tmp",
          "\t}",
          "}",
          "",
          "global Buffer b = new Buffer()",
          "",
          "Thread(1, 'Productor'){",
          "\tb.depositar(42)",
          "\tb.depositar(99)",
          "}",
          "",
          "Thread(1, 'Consumidor'){",
          "\tprint(b.retirar())",
          "\tprint(b.retirar())",
          "}",
        ].join("\n"),
        razon: "Igual que el anterior pero con dos variables de condición explícitas — más preciso: el productor notifica solo a consumidores y viceversa",
      },
    ],
  },
  {
    categoria: "Canales",
    ejemplos: [
      {
        id: "ch0",
        titulo: "Send y Receive básico",
        texto: [
          "global Channel c = new Channel()",
          "",
          "Thread(1, 'Emisor'){",
          "\tc.send(42)",
          "\tc.send(99)",
          "}",
          "",
          "Thread(1, 'Receptor'){",
          "\tlocal x = c.receive()",
          "\tprint(x)",
          "\tlocal y = c.receive()",
          "\tprint(y)",
          "}",
        ].join("\n"),
        razon: "Canal básico: el receptor bloquea hasta que el emisor manda — send no bloqueante, receive sí",
      },
      {
        id: "ch1",
        titulo: "Race condition con canal compartido",
        texto: [
          "global Channel c1 = new Channel()",
          "global Channel c2 = new Channel()",
          "",
          "// P1 y P2 reciben un valor, suman 1 y lo devuelven por el mismo canal",
          "// P3 manda los valores y espera los resultados por el mismo canal",
          "// PROBLEMA: si el scheduler no le da turno a P1/P2 antes de que",
          "// P3 haga receive(), P3 puede consumir su propio mensaje",
          "// → el resultado no siempre es 32",
          "",
          "process P1(c1){",
          "\tlocal x = c1.receive()",
          "\tlocal r1 = x + 1",
          "\tc1.send(r1)",
          "}",
          "",
          "process P2(c2){",
          "\tlocal y = c2.receive()",
          "\tlocal r2 = y + 1",
          "\tc2.send(r2)",
          "}",
          "",
          "process P3(c1, c2){",
          "\tc1.send(10)",
          "\tc2.send(20)",
          "\tlocal r1 = c1.receive()",
          "\tlocal r2 = c2.receive()",
          "\tprint(r1 + r2)",
          "}",
        ].join("\n"),
        razon: "Race condition: P3 usa el mismo canal para enviar y recibir. Si el scheduler no le da turno a P1/P2 a tiempo, P3 consume su propio mensaje y el resultado es 31 en vez de 32",
      },
      {
        id: "ch1b",
        titulo: "Pipeline con canales separados",
        texto: [
          "global Channel c1in  = new Channel()",
          "global Channel c1out = new Channel()",
          "global Channel c2in  = new Channel()",
          "global Channel c2out = new Channel()",
          "",
          "process P1(c1in, c1out){",
          "\tlocal x = c1in.receive()",
          "\tc1out.send(x + 1)",
          "}",
          "",
          "process P2(c2in, c2out){",
          "\tlocal y = c2in.receive()",
          "\tc2out.send(y + 1)",
          "}",
          "",
          "process P3(c1in, c1out, c2in, c2out){",
          "\tc1in.send(10)",
          "\tc2in.send(20)",
          "\tlocal r1 = c1out.receive()",
          "\tlocal r2 = c2out.receive()",
          "\tprint(r1 + r2)",
          "}",
        ].join("\n"),
        razon: "Canales separados para entrada y salida de cada worker — P3 no puede consumir su propio mensaje, siempre imprime 32",
      },
      {
        id: "ch5",
        titulo: "Sleep en canal (productor lento)",
        texto: [
          "global Channel c = new Channel()",
          "",
          "process Productor(c){",
          "\tc.send(1)",
          "\tsleep(3)",
          "\tc.send(2)",
          "\tsleep(3)",
          "\tc.send(3)",
          "}",
          "",
          "process Consumidor(c){",
          "\tprint(c.receive())",
          "\tprint(c.receive())",
          "\tprint(c.receive())",
          "}",
        ].join("\n"),
        razon: "El productor duerme 3 pasos entre cada envío — el consumidor bloquea en receive() hasta que el productor se despierte y mande el siguiente valor",
      },
      {
        id: "ch4",
        titulo: "Threads dinámicos (servidor con loop)",
        texto: [
          "global Channel pedidos = new Channel()",
          "",
          "process Cliente(pedidos){",
          "\tpedidos.send(10)",
          "\tpedidos.send(20)",
          "\tpedidos.send(30)",
          "}",
          "",
          "process Servidor(pedidos){",
          "\trepeat(3){",
          "\t\tlocal req = pedidos.receive()",
          "\t\tThread(1, 'Worker'){",
          "\t\t\tprint(req + 1)",
          "\t\t}",
          "\t}",
          "}",
        ].join("\n"),
        razon: "El servidor recibe 3 pedidos en loop y lanza un Thread dinámico por cada uno — los workers se crean en runtime, no al inicio",
      },
      {
        id: "ch3",
        titulo: "Threads dentro de proceso",
        texto: [
          "global Channel tareas = new Channel()",
          "global Channel resultados = new Channel()",
          "",
          "process Coordinador(tareas, resultados){",
          "\tThread(3, 'Worker'){",
          "\t\tlocal t = tareas.receive()",
          "\t\tresultados.send(t + 1)",
          "\t}",
          "\ttareas.send(10)",
          "\ttareas.send(20)",
          "\ttareas.send(30)",
          "\tlocal r1 = resultados.receive()",
          "\tlocal r2 = resultados.receive()",
          "\tlocal r3 = resultados.receive()",
          "\tprint(r1 + r2 + r3)",
          "}",
        ].join("\n"),
        razon: "El proceso lanza 3 workers, les manda tareas por canal, espera los 3 resultados y los suma — siempre imprime 33",
      },
      {
        id: "ch2",
        titulo: "Request por canal",
        texto: [
          "global Channel pedidos = new Channel()",
          "global Channel respuestas = new Channel()",
          "",
          "process Servidor(pedidos, respuestas){",
          "\tlocal req = pedidos.receive()",
          "\tlocal resultado = req.a + req.b",
          "\trespuestas.send(resultado)",
          "}",
          "",
          "process Cliente(pedidos, respuestas){",
          "\tlocal req = new Request()",
          "\treq.a = 10",
          "\treq.b = 32",
          "\tpedidos.send(req)",
          "\tlocal res = respuestas.receive()",
          "\tprint(res)",
          "}",
        ].join("\n"),
        razon: "Cliente envía un Request con campos a y b, el servidor lo procesa y devuelve el resultado por otro canal",
      },
    ],
  },
];
