export default [
  {
    categoria: "Básicos",
    ejemplos: [
      {
        id: "b0",
        titulo: "Interleaving",
        texto: [
          "Thread(2){",
          "\tprint('rojo')",
          "}",
          "",
          "Thread(2){",
          "\tprint('azul')",
          "}",
        ].join("\n"),
        razon: "Dos pares de threads imprimiendo colores — muestra interleaving básico",
      },
      {
        id: "b1",
        titulo: "Lectura vieja",
        texto: [
          "global Int n = 0",
          "",
          "Thread(1){",
          "\tn = n + 1",
          "}",
          "",
          "Thread(1){",
          "\tprint(n)",
          "}",
        ].join("\n"),
        razon: "Thread suma global e imprime — la lectura puede ser anterior a la escritura del otro thread",
      },
      {
        id: "b2",
        titulo: "Race condition",
        texto: [
          "global Int n = 0",
          "",
          "Thread(2){",
          "\tn = n + 1",
          "}",
        ].join("\n"),
        razon: "Dos threads incrementando la misma variable — clásico ejemplo de pérdida de escritura",
      },
      {
        id: "b3",
        titulo: "Suma cruzada",
        texto: [
          "global Int x = 0",
          "global Int y = 0",
          "",
          "Thread(1){",
          "\ty = x + 1",
          "}",
          "",
          "Thread(1){",
          "\tx = y + 1",
          "}",
        ].join("\n"),
        razon: "Dos threads con variables que dependen entre sí — pérdida de suma cruzada",
      },
    ],
  },
  {
    categoria: "Control de flujo",
    ejemplos: [
      {
        id: "c0",
        titulo: "While compartido",
        texto: [
          "global Int n = 1",
          "",
          "Thread(2){",
          "\twhile(n == 1){",
          "\t\tn = n + 1",
          "\t}",
          "}",
        ].join("\n"),
        razon: "Dos threads esperando la misma condición compartida",
      },
      {
        id: "c1",
        titulo: "While con print",
        texto: [
          "global Int n = 0",
          "",
          "Thread(1){",
          "\twhile(n < 2){",
          "\t\tprint(n)",
          "\t}",
          "}",
          "",
          "Thread(1){",
          "\tn = n + 1",
          "\tn = n + 1",
          "}",
        ].join("\n"),
        razon: "Un thread puede leer valores viejos mientras el otro actualiza",
      },
      {
        id: "c2",
        titulo: "Repeat",
        texto: [
          "global Int n = 0",
          "",
          "Thread(2){",
          "\trepeat(3){",
          "\t\tn = n + 1",
          "\t}",
          "}",
        ].join("\n"),
        razon: "Dos threads repitiendo un bloque 3 veces — posible pérdida de incrementos",
      },
      {
        id: "c3",
        titulo: "For",
        texto: [
          "global Int n = 0",
          "",
          "Thread(2){",
          "\tfor(local Int i = 0; i < 3; i = i + 1){",
          "\t\tn = n + 1",
          "\t}",
          "}",
        ].join("\n"),
        razon: "Dos threads suman n 3 veces cada uno con for",
      },
      {
        id: "c4",
        titulo: "For-each",
        texto: [
          "global Int n = 0",
          "",
          "Thread(1){",
          "\tfor(x : [1,2,3]){",
          "\t\tn = n + x",
          "\t}",
          "}",
        ].join("\n"),
        razon: "Suma los elementos de una lista con for-each",
      },
    ],
  },
  {
    categoria: "Semáforos",
    ejemplos: [
      {
        id: "s0",
        titulo: "Mutex básico",
        texto: [
          "global Int contador = 0",
          "global Semaphore mutex = new Semaphore(1)",
          "",
          "Thread(2){",
          "\tmutex.acquire()",
          "\tcontador = contador + 1",
          "\tmutex.release()",
          "}",
        ].join("\n"),
        razon: "Mutex: 2 threads incrementan contador con exclusión mutua",
      },
      {
        id: "s1",
        titulo: "Split mutex",
        texto: [
          "global Semaphore turnoA = new Semaphore(1)",
          "global Semaphore turnoB = new Semaphore(0)",
          "",
          "Thread(1, 'A'){",
          "\twhile(true){",
          "\t\tturnoA.acquire()",
          "\t\tprint('A')",
          "\t\tturnoB.release()",
          "\t}",
          "}",
          "",
          "Thread(1, 'B'){",
          "\twhile(true){",
          "\t\tturnoB.acquire()",
          "\t\tprint('B')",
          "\t\tturnoA.release()",
          "\t}",
          "}",
        ].join("\n"),
        razon: "Split mutex: A y B se alternan estrictamente imprimiendo su letra",
      },
      {
        id: "s2",
        titulo: "Productor-Consumidor",
        texto: [
          "global Int buffer = 0",
          "global Int producido = 0",
          "global Semaphore vacio = new Semaphore(1)",
          "global Semaphore lleno = new Semaphore(0)",
          "",
          "Thread(1, 'Productor'){",
          "\tvacio.acquire()",
          "\tproducido = producido + 1",
          "\tbuffer = producido",
          "\tprint(buffer)",
          "\tlleno.release()",
          "}",
          "",
          "Thread(1, 'Consumidor'){",
          "\tlleno.acquire()",
          "\tlocal Int item = buffer",
          "\tvacio.release()",
          "\tprint(item)",
          "}",
        ].join("\n"),
        razon: "Productor-Consumidor: buffer de tamaño 1 sincronizado con semáforos",
      },
      {
        id: "s3",
        titulo: "Lector-Escritor",
        texto: [
          "global Int lectores = 0",
          "global Semaphore mutexLectores = new Semaphore(1)",
          "global Semaphore escritura = new Semaphore(1)",
          "global Int dato = 0",
          "",
          "Thread(2, 'Lector'){",
          "\tmutexLectores.acquire()",
          "\tlectores = lectores + 1",
          "\tif(lectores == 1){",
          "\t\tescritu ra.acquire()",
          "\t}",
          "\tmutexLectores.release()",
          "\tprint(dato)",
          "\tmutexLectores.acquire()",
          "\tlectores = lectores - 1",
          "\tif(lectores == 0){",
          "\t\tescritu ra.release()",
          "\t}",
          "\tmutexLectores.release()",
          "}",
          "",
          "Thread(1, 'Escritor'){",
          "\tescritu ra.acquire()",
          "\tdato = dato + 1",
          "\tescritu ra.release()",
          "}",
        ].join("\n").replace(/escritu ra/g, "escritura"),
        razon: "Lector-Escritor: múltiples lectores simultáneos, escritor con exclusión total",
      },
      {
        id: "s4",
        titulo: "Array de semáforos",
        texto: [
          "global Int contador = 0",
          "global Semaphore[] sems = new Semaphore[2](1)",
          "",
          "Thread(2){",
          "\tlocal Int id = getId()",
          "\tsems[id].acquire()",
          "\tcontador = contador + 1",
          "\tsems[id].release()",
          "}",
        ].join("\n"),
        razon: "Cada thread usa su propio semáforo del array",
      },
      {
        id: "s5",
        titulo: "Semáforo débil",
        texto: [
          "global Semaphore s = new Semaphore(0)",
          "",
          "Thread(3, 'Esperando'){",
          "\tlocal Int id = getId()",
          "\ts.acquire()",
          "\tprint(id)",
          "}",
          "",
          "Thread(1, 'Liberador'){",
          "\ts.release()",
          "\ts.release()",
          "\ts.release()",
          "}",
        ].join("\n"),
        razon: "Semáforo débil: los threads se despiertan en orden aleatorio — el print puede salir en cualquier orden",
      },
      {
        id: "s6",
        titulo: "Semáforo fuerte",
        texto: [
          "global Semaphore s = new Semaphore(0, true)",
          "",
          "Thread(3, 'Esperando'){",
          "\tlocal Int id = getId()",
          "\ts.acquire()",
          "\tprint(id)",
          "}",
          "",
          "Thread(1, 'Liberador'){",
          "\ts.release()",
          "\ts.release()",
          "\ts.release()",
          "}",
        ].join("\n"),
        razon: "Semáforo fuerte (FIFO): los threads se despiertan en el orden en que llegaron — el print siempre sale en el mismo orden",
      },
    ],
  },
  {
    categoria: "Algoritmos",
    ejemplos: [
      {
        id: "a0",
        titulo: "Bakery",
        texto: [
          "global List ticket = [0,0]",
          "global List pidiendoTicket = [false,false]",
          "global Int n = 2",
          "global Int seccionCritica = 0",
          "",
          "Thread(2){",
          "\tlocal Int id = getId()",
          "\tpidiendoTicket[id] = true",
          "\tticket[id] = 1 + ticket.maximum()",
          "\tpidiendoTicket[id] = false",
          "\tfor(local Int j=0;j<n;j=j+1){",
          "\t\twhile(pidiendoTicket[j]){",
          "\t\t}",
          "\t\twhile(ticket[j]!=0&&(ticket[j]<ticket[id]||(ticket[j]==ticket[id]&&j<id))){",
          "\t\t}",
          "\t}",
          "\tseccionCritica = seccionCritica + 1",
          "\tticket[id] = 0",
          "}",
        ].join("\n"),
        razon: "Algoritmo de Bakery (Lamport): exclusión mutua sin semáforos",
      },
      {
        id: "a1",
        titulo: "Funciones",
        texto: [
          "global Int contador = 0",
          "",
          "function incrementar(Int x) {",
          "\treturn x + 1",
          "}",
          "",
          "Thread(2) {",
          "\tlocal Int leido = contador",
          "\tlocal Int nuevo = incrementar(leido)",
          "\tcontador = nuevo",
          "}",
        ].join("\n"),
        razon: "Race condition visible a través de llamadas a función",
      },
    ],
  },
  {
    categoria: "Errores",
    ejemplos: [
      {
        id: "e0",
        titulo: "Variable no declarada",
        texto: [
          "Thread(1){",
          "\tcontador = contador + 1",
          "}",
        ].join("\n"),
        razon: "Usar una variable sin declararla — error de runtime",
      },
      {
        id: "e1",
        titulo: "Typo en nombre",
        texto: [
          "global Int contador = 0",
          "",
          "Thread(1){",
          "\tcontadorr = contadorr + 1",
          "}",
        ].join("\n"),
        razon: "Error de tipeo en el nombre de una variable",
      },
      {
        id: "e2",
        titulo: "Sintaxis rota",
        texto: [
          "global Int n = 0",
          "",
          "Thread(2){",
          "\tif(n == 0{",
          "\t\tn = n + 1",
          "\t}",
          "}",
        ].join("\n"),
        razon: "Paréntesis sin cerrar en el if — error de parse",
      },
      {
        id: "e3",
        titulo: "Índice fuera de rango",
        texto: [
          "global List nums = [1, 2, 3]",
          "",
          "Thread(1){",
          "\tprint(nums[5])",
          "}",
        ].join("\n"),
        razon: "Acceso a un índice que no existe en la lista",
      },
    ],
  },
  {
    categoria: "Clases",
    ejemplos: [
      {
        id: "cl0",
        titulo: "Contador compartido",
        texto: [
          "class Contador {",
          "\tlocal Int valor = 0",
          "",
          "\tconstructor(Int inicial) {",
          "\t\tvalor = inicial",
          "\t}",
          "",
          "\tfunction incrementar() {",
          "\t\tvalor = valor + 1",
          "\t}",
          "",
          "\tfunction getValor() {",
          "\t\treturn valor",
          "\t}",
          "}",
          "",
          "global Contador c = new Contador(0)",
          "",
          "Thread(2){",
          "\tc.incrementar()",
          "\tprint(c.getValor())",
          "}",
        ].join("\n"),
        razon: "Race condition clásica: dos threads incrementan el mismo objeto — el interleaving dentro de incrementar() puede causar pérdida de escritura",
      },
      {
        id: "cl1",
        titulo: "Instancias locales (sin race)",
        texto: [
          "class Contador {",
          "\tlocal Int valor = 0",
          "",
          "\tconstructor(Int inicial) {",
          "\t\tvalor = inicial",
          "\t}",
          "",
          "\tfunction incrementar() {",
          "\t\tvalor = valor + 1",
          "\t}",
          "",
          "\tfunction getValor() {",
          "\t\treturn valor",
          "\t}",
          "}",
          "",
          "Thread(2){",
          "\tlocal Contador c = new Contador(0)",
          "\tc.incrementar()",
          "\tc.incrementar()",
          "\tprint(c.getValor())",
          "}",
        ].join("\n"),
        razon: "Cada thread crea su propia instancia local — no hay memoria compartida, no hay race condition",
      },
      {
        id: "cl2",
        titulo: "Contador con semáforo",
        texto: [
          "class Contador {",
          "\tlocal Int valor = 0",
          "",
          "\tconstructor(Int inicial) {",
          "\t\tvalor = inicial",
          "\t}",
          "",
          "\tfunction incrementar() {",
          "\t\tvalor = valor + 1",
          "\t}",
          "",
          "\tfunction getValor() {",
          "\t\treturn valor",
          "\t}",
          "}",
          "",
          "global Contador c = new Contador(0)",
          "global Semaphore mutex = new Semaphore(1)",
          "global Semaphore listo = new Semaphore(0)",
          "",
          "Thread(3, 'Escritor'){",
          "\tmutex.acquire()",
          "\tc.incrementar()",
          "\tmutex.release()",
          "\tlisto.release()",
          "}",
          "",
          "Thread(1, 'Lector'){",
          "\tlisto.acquire()",
          "\tlisto.acquire()",
          "\tlisto.acquire()",
          "\tprint(c.getValor())",
          "}",
        ].join("\n"),
        razon: "El lector espera a los 3 escritores con 3 acquires — siempre imprime 3 sin importar el interleaving",
      },
      {
        id: "cl3",
        titulo: "Estado inconsistente",
        texto: [
          "class Punto {",
          "\tlocal Int x = 0",
          "\tlocal Int y = 0",
          "",
          "\tfunction mover(Int nx, Int ny) {",
          "\t\tx = nx",
          "\t\ty = ny",
          "\t}",
          "",
          "\tfunction leer() {",
          "\t\treturn x + y",
          "\t}",
          "}",
          "",
          "global Punto p = new Punto()",
          "",
          "Thread(2, 'Escritor'){",
          "\tp.mover(10, 10)",
          "}",
          "",
          "Thread(2, 'Lector'){",
          "\tprint(p.leer())",
          "}",
        ].join("\n"),
        razon: "Sin semáforo, un lector puede ver x=10 e y=0 — un estado que nunca debería existir. El resultado puede ser 0, 10 o 20",
      },
      {
        id: "cl4",
        titulo: "this — delegación entre métodos",
        texto: [
          "class Contador {",
          "\tlocal Int valor = 0",
          "",
          "\tfunction incrementar() {",
          "\t\tvalor = valor + 1",
          "\t}",
          "",
          "\tfunction incrementarDos() {",
          "\t\tthis.incrementar()",
          "\t\tthis.incrementar()",
          "\t}",
          "",
          "\tfunction getValor() {",
          "\t\treturn valor",
          "\t}",
          "}",
          "",
          "global Contador c = new Contador(0)",
          "",
          "Thread(2){",
          "\tc.incrementarDos()",
          "\tprint(c.getValor())",
          "}",
        ].join("\n"),
        razon: "this llama a métodos de la misma instancia — el interleaving puede ocurrir entre los dos incrementar() internos, mostrando race condition dentro de la delegación",
      },
    ],
  },
  {
    categoria: "Monitores",
    ejemplos: [
      {
        id: "m0",
        titulo: "Exclusión mutua",
        texto: [
          "monitor Contador {",
          "\tlocal Int valor = 0",
          "",
          "\tfunction incrementar() {",
          "\t\tvalor = valor + 1",
          "\t\tprint(valor)",
          "\t}",
          "}",
          "",
          "global Contador c = new Contador()",
          "",
          "Thread(3){",
          "\tc.incrementar()",
          "}",
        ].join("\n"),
        razon: "El monitor garantiza exclusión mutua — solo un thread ejecuta incrementar() a la vez, nunca hay pérdida de escritura",
      },
      {
        id: "m1",
        titulo: "Productor-Consumidor",
        texto: [
          "monitor Buffer {",
          "\tlocal Int dato = 0",
          "\tlocal Bool lleno = false",
          "",
          "\tfunction depositar(Int v) {",
          "\t\twhile (lleno == true) {",
          "\t\t\twait()",
          "\t\t}",
          "\t\tdato = v",
          "\t\tlleno = true",
          "\t\tnotifyAll()",
          "\t}",
          "",
          "\tfunction retirar() {",
          "\t\twhile (lleno == false) {",
          "\t\t\twait()",
          "\t\t}",
          "\t\tlocal Int tmp = dato",
          "\t\tlleno = false",
          "\t\tnotifyAll()",
          "\t\treturn tmp",
          "\t}",
          "}",
          "",
          "global Buffer b = new Buffer()",
          "",
          "Thread(1, 'Productor'){",
          "\tb.depositar(42)",
          "\tb.depositar(99)",
          "}",
          "",
          "Thread(1, 'Consumidor'){",
          "\tprint(b.retirar())",
          "\tprint(b.retirar())",
          "}",
        ].join("\n"),
        razon: "Productor-Consumidor con monitor — el buffer de tamaño 1 se sincroniza con wait/notify sin semáforos explícitos",
      },
      {
        id: "m2",
        titulo: "Variables de condición explícitas",
        texto: [
          "monitor Buffer {",
          "\tcondition hayDato",
          "\tcondition hayEspacio",
          "\tlocal Int dato = 0",
          "\tlocal Bool lleno = false",
          "",
          "\tfunction depositar(Int v) {",
          "\t\twhile (lleno == true) {",
          "\t\t\thayEspacio.wait()",
          "\t\t}",
          "\t\tdato = v",
          "\t\tlleno = true",
          "\t\thayDato.notify()",
          "\t}",
          "",
          "\tfunction retirar() {",
          "\t\twhile (lleno == false) {",
          "\t\t\thayDato.wait()",
          "\t\t}",
          "\t\tlocal Int tmp = dato",
          "\t\tlleno = false",
          "\t\thayEspacio.notify()",
          "\t\treturn tmp",
          "\t}",
          "}",
          "",
          "global Buffer b = new Buffer()",
          "",
          "Thread(1, 'Productor'){",
          "\tb.depositar(42)",
          "\tb.depositar(99)",
          "}",
          "",
          "Thread(1, 'Consumidor'){",
          "\tprint(b.retirar())",
          "\tprint(b.retirar())",
          "}",
        ].join("\n"),
        razon: "Igual que el anterior pero con dos variables de condición explícitas — más preciso: el productor notifica solo a consumidores y viceversa",
      },
    ],
  },
];
